/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonVariation, Color, Size } from "./components/key-button/key-button";
export namespace Components {
    interface KeyButton {
        "color": Color;
        "size": Size;
        "variation": ButtonVariation;
    }
}
declare global {
    interface HTMLKeyButtonElement extends Components.KeyButton, HTMLStencilElement {
    }
    var HTMLKeyButtonElement: {
        prototype: HTMLKeyButtonElement;
        new (): HTMLKeyButtonElement;
    };
    interface HTMLElementTagNameMap {
        "key-button": HTMLKeyButtonElement;
    }
}
declare namespace LocalJSX {
    interface KeyButton {
        "color"?: Color;
        "size"?: Size;
        "variation"?: ButtonVariation;
    }
    interface IntrinsicElements {
        "key-button": KeyButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "key-button": LocalJSX.KeyButton & JSXBase.HTMLAttributes<HTMLKeyButtonElement>;
        }
    }
}
